app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name='login.html', authentication_form=LoginForm), name='login'),
]

conversation/urls.py
from django.urls import path 
from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

treasurehub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/base.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <script src="http://cdn.tailwindcss.com"></script>

    <title>{% block title %}{% endblock %} | TreasureHub</title>
  </head>

  <body class="bg-gray-100">

    <nav class="py-6 px-4 md:px-8 lg:px-10 flex justify-between items-center border-b border-yellow-500 bg-black">
        <a href="/" class="text-lg md:text-xl lg:text-2xl font-semibold text-white hover:text-yellow-500">TreasureHub</a>

        <div class="md:space-x-6">
            <a href="{% url 'item:new' %}" class="text-base md:text-lg lg:text-xl font-semibold hover:text-yellow-500 text-white">New item</a>
            <a href="{% url 'item:items' %}" class="text-base md:text-lg lg:text-xl font-semibold hover:text-yellow-500 text-white">Browse</a>

            {% if request.user.is_authenticated %}
            <a href="{% url 'conversation:inbox' %}" class="px-4 md:px-6 py-2 md:py-3 text-base md:text-lg lg:text-xl font-semibold bg-yellow-500 text-white rounded-xl hover:bg-yellow-600 hover:text-yellow-500">Inbox</a>
            <a href="{% url 'dashboard:index' %}" class="px-4 md:px-6 py-2 md:py-3 text-base md:text-lg lg:text-xl font-semibold bg-yellow-500 text-white rounded-xl hover:bg-yellow-600 hover:text-yellow-500">Dashboard</a>
            {% else %}
            <a href="{% url 'app:signup' %}" class="px-4 md:px-6 py-2 md:py-3 text-base md:text-lg lg:text-xl font-semibold bg-yellow-500 text-white rounded-xl hover:bg-yellow-600 hover:text-yellow-500">Sign up</a>
            <a href="{% url 'app:login' %}" class="px-4 md:px-6 py-2 md:py-3 text-base md:text-lg lg:text-xl font-semibold bg-yellow-500 text-white rounded-xl hover:bg-yellow-600 hover:text-yellow-500">Log in</a>
            {% endif %}

        </div>

    </nav>

    <div class="p-4 md:p-6 lg:p-10">{% block content %} {% endblock %}</div>

    <footer class="py-6 px-4 md:px-8 lg:px-10 flex flex-col md:flex-row justify-between bg-black text-white">
        <div class="mb-6 md:mb-0 md:w-2/3 md:pr-10">
            <h3 class="mb-5 font-semibold text-lg md:text-xl lg:text-2xl">About</h3>
            <p class="text-base md:text-lg lg:text-xl text-gray-500">Welcome to our thriving online marketplace, designed exclusively for Dungeons & Dragons enthusiasts! At TreasureHub, we understand the unique needs of the D&D community, and we're here to enhance your gaming experience by providing a curated selection of products tailored just for you.</p>
        </div>

        <div class="md:w-1/3">
            <h3 class="mb-5 font-semibold text-lg md:text-xl lg:text-2xl">Menu</h3>
            <ul class="space-y-2">
                <li><a href="#" class="text-base md:text-lg lg:text-xl text-yellow-300 hover:text-yellow-600">About</a></li>
                <li><a href="#" class="text-base md:text-lg lg:text-xl text-yellow-300 hover:text-yellow-600">Contact</a></li>
                <li><a href="#" class="text-base md:text-lg lg:text-xl text-yellow-300 hover:text-yellow-600">Privacy Policy</a></li>
                <li><a href="#" class="text-base md:text-lg lg:text-xl text-yellow-300 hover:text-yellow-600">Terms of Use</a></li>
            </ul>
        </div>
    </footer>

</body>
</html>

app/templates/contact.html
{% extends 'base.html' %}
{% block title %}Contact{% endblock %}
{% block content %}
    <h1>Contact</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block title %}Welcome{% endblock %}
{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest Items</h2>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {% for item in items %}
                <div class="mb-6">
                    <a href="{% url 'item:detail' item.id %}">
                        <div class="overflow-hidden rounded-xl">
                            <img src="{{ item.image.url }}" class="w-full h-auto">
                        </div>
                        <div class='p-6 bg-white rounded-b-xl'>
                            <h2 class="text-xl md:text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: ${{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {% for category in categories %}
                <div class="mb-6">
                    <a href="#">
                        <div class='p-6 bg-white rounded-b-xl'>
                            <h2 class="text-xl md:text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} item(s)</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block title %}Log In{% endblock%}

{% block content %}
    <div class="w-1/2 my-6 p-8 mx-auto bg-yellow-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Log in</h1>

        <form method='post' action=".">
            {% csrf_token %}

            <div class="mb-4">
                <label class="inline-block mb-2">Username:</label><br>
                {{ form.username }}
            </div>


            <div class="mb-4">
                <label class="inline-block mb-2">Password:</label><br>
                {{ form.password }}
            </div>


            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-8 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <button class="py-5 px-10 text-lg bg-yellow-500 text-white hover:text-yellow-400 hover:bg-yellow_600 rounded-xl">Submit!</button>
    </div>
{% endblock %}

app/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign up{% endblock%}

{% block content %}
    <div class="w-1/2 my-6 mx-auto bg-yellow-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Sign up</h1>

        <form method='post' action=".">
            {% csrf_token %}


            <div class="mb-3">
                <label class="inline-block mb-2">Username:</label><br>
                {{ form.username }}
            </div>

            <div class="mb-4">
                <label class="inline-block mb-2">Email:</label><br>
                {{ form.email }}
            </div>

            <div class="mb-4">
                <label class="inline-block mb-2">Password:</label><br>
                {{ form.password1 }}
            </div>

            <div class="mb-4">
                <label class="inline-block mb-2">Repeat Password:</label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors  or form.non_field_errors %}
                <div class="mb-4 p-6 bg-red-200 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <button class="py-5 px-10 text-lg bg-yellow-500 text-white hover:text-yellow-400 hover:bg-yellow_600 rounded-xl">Submit!</button>
        </form>
    </div>
{% endblock %}